### ISSUE TITLE
Google Maps location do not appear

### ISSUE THREAD

**Issue by dfranquesa** [eReuse/eReuseAndroidApp#1]
I've done a locate but google maps do not appear. Currently I'm running Beta "version that includes Snapshot a device option"

**Comment by bustawin** [comment]
Is the internal apk or the app from the Google Play Store?

**Comment by dfranquesa** [comment]
Internal apk.

El dia 17 febr. 2017 8:18 p. m., "Xavier" <notifications@github.com> va
escriure:

**Comment by bustawin** [comment]
Apks generated by Jamgo (i.e. internal apks) are not signed and do not have the credentials to access the google API; I am the one doing it from the code they publish in this repo.
